/* Generated by Yosys 0.58+80 (git sha1 2613c1c0a, clang++ 13.0.0 -fPIC -O3) */

module \s27.aig (_18_, _19_, _20_, _21_, _22_, _26_);
  input _18_;
  wire _18_;
  input _19_;
  wire _19_;
  input _20_;
  wire _20_;
  input _21_;
  wire _21_;
  input _22_;
  wire _22_;
  output _26_;
  wire _26_;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  (* init = 1'h0 *)
  wire _23_;
  (* init = 1'h0 *)
  wire _24_;
  (* init = 1'h0 *)
  wire _25_;
  assign _00_ = _15_ & _10_;
  assign _02_ = _01_ & _17_;
  assign _04_ = _17_ & _11_;
  assign _06_ = _05_ & _03_;
  assign _07_ = _06_ & _14_;
  assign _08_ = _26_ & _21_;
  assign _09_ = _01_ & _12_;
  assign _16_ = _23_ & _13_;
  \$ff  #(
    .WIDTH(32'd1)
  ) _35_ (
    .D(_07_),
    .Q(_23_)
  );
  \$ff  #(
    .WIDTH(32'd1)
  ) _36_ (
    .D(_08_),
    .Q(_24_)
  );
  \$ff  #(
    .WIDTH(32'd1)
  ) _37_ (
    .D(_09_),
    .Q(_25_)
  );
  assign _10_ = ~_18_;
  assign _01_ = ~_00_;
  assign _03_ = ~_02_;
  assign _05_ = ~_04_;
  assign _26_ = ~_07_;
  assign _11_ = ~_19_;
  assign _12_ = ~_20_;
  assign _13_ = ~_21_;
  assign _14_ = ~_24_;
  assign _15_ = ~_25_;
  assign _17_ = ~_16_;
endmodule
