/* Generated by Yosys 0.58+80 (git sha1 2613c1c0a, clang++ 13.0.0 -fPIC -O3) */

module top(input_0, input_1, input_2, input_3, input_4, po0, po1,clock);
  input clock;
  input input_0;
  wire input_0;
  input input_1;
  wire input_1;
  input input_2;
  wire input_2;
  input input_3;
  wire input_3;
  input input_4;
  wire input_4;
  output po0;
  wire po0;
  output po1;
  wire po1;
  wire new_n0;
  wire new_n1;
  wire signal_10;
  wire signal_11;
  wire signal_6;
  wire signal_7;
  wire signal_8;
  wire signal_9;
  assign signal_6 = 4'h8 >> { input_1, input_0 };
  assign signal_7 = 4'h8 >> { input_3, input_1 };
  assign signal_8 = 4'h2 >> { signal_7, input_2 };
  assign signal_9 = 4'h1 >> { signal_8, signal_6 };
  assign signal_10 = 4'h2 >> { signal_7, input_4 };
  assign signal_11 = 4'h1 >> { signal_10, signal_8 };
  assign po0 = 2'h1 >> signal_9;
  assign po1 = 2'h1 >> signal_11;
  assign new_n0 = 1'h0;
  assign new_n1 = 1'h1;
endmodule
